Allow microsoft-ui-xaml to support multiple sets of styles (#3690)
* update customtask

* update project to use the customtool and support UseVisualStyle

* support new flag in api

* missing one file change for custombuild task

* update to new api and address some comments

* fix the ->

* script to move master xaml to v2.5 and add them to proj

* manually correct the missing items

* vcxproj back to UTF8

* standard the name and replace previous with 2dot5

* batch remove last line for project

* remove pips and address commentss

* trim last line

* remove newline at the end of file

* fix ##[error]dev\dll\XamlControlsResources.cpp(249,0): Error C26449: gsl::span or std::string_view created from a temporary will be invalid when the temporary is invalidated (gsl.view).

* remove return type in lambda

* remove Expander_v2.5.xaml, move merge.bat to tools and fix the test failure

* fix test